pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: minikube
                          namespace: ci
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: luke_docker_hub
                                    image: alpine:latest
                                    command: env
                                    privileged: false
                  cloneCodebase: true
              name: Build
              identifier: build
              variables:
                  - name: testing_env
                    type: String
                    value: fdadsfdsdfs
    properties:
        ci:
            codebase:
                repoName: mvcapp
                connectorRef: luke_github
                build: <+input>
    projectIdentifier: luke
    orgIdentifier: default
    name: mvcapp
    identifier: mvcapp
